### ISSUE TITLE
Stable-Repo seems to get deps from latest filled in

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.repositories#621] opened 2020-02-20 21:05 UTC
The current stable repo really contains wrong dependencies for e.g. javascript!
It seems that the deps from the latest repo somehow slip into stable repo.

happens with Javascript, iot adapter and more

**Comment by AlCalzone** [comment] 2020-02-21 06:37
This seems weird:
gulp task stable processes the latest-repo file
https://github.com/ioBroker/ioBroker.repositories/blob/ea6c11cf7c2fb10d0e028f8136e748c7e5b57c22/gulpfile.js#L27

gulp task latest processes the stable repo file
https://github.com/ioBroker/ioBroker.repositories/blob/ea6c11cf7c2fb10d0e028f8136e748c7e5b57c22/gulpfile.js#L51

**Comment by GermanBluefox** [comment] 2020-03-03 09:09
It is not a bug, it is a feature....
But must be changed. I read ALWAYS github latest/master.

To solve the problem, the npm must be read (whole package :( ) and this is awful.

**Comment by Apollon77** [comment] 2020-03-03 09:13
Ahhhh I see :-( So just a matter of time till it broke ;-)

**Comment by AlCalzone** [comment] 2020-03-03 10:07
Just an idea, not sure if this is better:
What if we automatically updated the dependencies when a PR for the stable repo is merged?
1. detect which adapters were updated
2. download their npm package, extract io-package.json
3. update stable repo with that info.

This way, the update process would be gradual instead of doing all the work when the repo file is updated.

**Comment by GermanBluefox** [comment] 2020-03-04 10:41
Done.

**Closed by GermanBluefox** 2020-03-04 10:41 UTC
